=== scotas/ols/bin/sqlunit.dtd
<!--
  $Id: sqlunit.dtd,v 1.1 2010/09/06 18:31:53 mochoa Exp $
  $Source: /cvsroot/dbprism/odi/bin/sqlunit.dtd,v $
  This is the DTD for creating SQLUnit test cases in XML
-->

<!-- Describing common elements -->
<!ELEMENT skip (#PCDATA)>
  <!ATTLIST skip
    value (true|false) "false">
<!ELEMENT severity (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT classifiers ((severity)?, (category)?)>
<!ELEMENT stmt (#PCDATA)>
<!ELEMENT param (#PCDATA)>
  <!ATTLIST param
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    type CDATA #REQUIRED
    scale CDATA #IMPLIED
    typename CDATA #IMPLIED
    is-null (true|false) "false"
    inout (in|out|inout) "in">
<!ELEMENT sql (stmt, (param)*)>
  <!ATTLIST sql
    id CDATA #IMPLIED
    connection-id CDATA #IMPLIED>
<!ELEMENT call (stmt, (param)*)>
  <!ATTLIST call
    id CDATA #IMPLIED
    connection-id CDATA #IMPLIED>
<!ELEMENT arg EMPTY>
  <!ATTLIST arg
    name CDATA #REQUIRED
    value CDATA #IMPLIED
    type CDATA #IMPLIED>
<!ELEMENT typedef EMPTY>
  <!ATTLIST typedef
    typename CDATA #REQUIRED
    classname CDATA #REQUIRED>
<!ELEMENT constructorArgs (arg)*>
<!ELEMENT methodArgs (arg)*>
<!ELEMENT methodinvoker ((constructorArgs)*,(methodArgs)*)>
  <!ATTLIST methodinvoker
    static (true|false) "false"
    class CDATA #REQUIRED
    method CDATA #REQUIRED>
<!ELEMENT dynamicsql ((constructorArgs)*,(methodArgs)*)>
  <!ATTLIST dynamicsql
    static (true|false) "false"
    class CDATA #REQUIRED
    method CDATA #REQUIRED>
<!ELEMENT include EMPTY>
  <!ATTLIST include
    file CDATA #REQUIRED
    connection-id CDATA #IMPLIED>
<!ELEMENT set (((sql|call),result)?|(constructorArgs*,methodArgs*)?)>
  <!ATTLIST set
    name CDATA #REQUIRED
    value CDATA #IMPLIED
    static (true|false) "false"
    class CDATA #IMPLIED
    method CDATA #IMPLIED>

<!-- Describing the match element used for fuzzy matching -->
<!ELEMENT match (arg)*>
  <!ATTLIST match
    resultset-id CDATA #IMPLIED
    row-id CDATA #IMPLIED
    col-id CDATA #IMPLIED
    matcher CDATA #REQUIRED>

<!-- Describing a failure as a result of processing an SQL statement -->
<!ELEMENT code (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT exception ((code)?, (message)?)>

<!-- Describing the connection element -->
<!ELEMENT driver (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT jarfile-url (#PCDATA)>
<!ELEMENT datasource (#PCDATA)>
<!ELEMENT jndi (arg)*>
<!ELEMENT typemap (typedef)*>
<!ELEMENT connection (((driver,url,user,password,(jarfile-url)?)|(datasource,jndi))?)>
  <!ATTLIST connection 
    connection-id CDATA #IMPLIED
    extern CDATA #IMPLIED
    server-name CDATA #IMPLIED
    transaction-support (on|off|implicit) "on"
    reconnect-on-failure (on|off) "off">

<!-- Describing the foreach element -->
<!ELEMENT foreach (sql)*>
  <!ATTLIST foreach
    param CDATA #REQUIRED
    values CDATA #IMPLIED
    start CDATA #IMPLIED
    stop CDATA #IMPLIED
    step CDATA #IMPLIED
    count CDATA #IMPLIED>

<!-- Defining the funcdef element -->
<!ELEMENT funcdef EMPTY>
  <!ATTLIST funcdef
    name CDATA #REQUIRED
    query CDATA #REQUIRED
    description CDATA #IMPLIED>

<!-- Defining the subdef element -->
<!ELEMENT subdef ((param)*)>
  <!ATTLIST subdef
    name CDATA #REQUIRED
    query CDATA #REQUIRED
    description CDATA #IMPLIED
    type (sql|call) "sql">

<!-- Describing the setup element -->
<!ELEMENT setup ((set)*, (funcdef)*, (subdef)*, (((sql)*,(foreach)*)|(include)*))>

<!-- Defining the subparam element -->
<!ELEMENT subparam EMPTY>
  <!ATTLIST subparam
    name CDATA #REQUIRED
    value CDATA #REQUIRED>

<!-- Defining the sub element -->
<!ELEMENT sub ((subparam)*)>
  <!ATTLIST sub
    lookup CDATA #REQUIRED
    connection-id CDATA #IMPLIED>

<!-- Describing the prepare element -->
<!ELEMENT prepare ((set)*,(sql)*,(foreach)*)>

<!-- Describing the test element -->
<!ELEMENT updatecount (#PCDATA)>
<!ELEMENT col (#PCDATA)>
  <!ATTLIST col
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    type CDATA #REQUIRED>
<!ELEMENT row ((col)+)>
  <!ATTLIST row
    id CDATA #REQUIRED
    partial (true|false) "false">
<!ELEMENT resultset ((row)*)>
  <!ATTLIST resultset
    id CDATA #REQUIRED
    partial (true|false) "false"
    rowcount CDATA #IMPLIED
    order-by CDATA #IMPLIED>
<!ELEMENT field (#PCDATA|struct)*>
  <!ATTLIST field
    name CDATA #REQUIRED>
<!ELEMENT struct (field)*>
<!ELEMENT outparam (#PCDATA|resultset|struct)*>
  <!ATTLIST outparam
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    type CDATA #REQUIRED>
<!ELEMENT result ((((outparam)*, (updatecount)?, (resultset)*)+|((outparam)*, exception))?)>
  <!ATTLIST result
    id CDATA #IMPLIED
    echo (true|false) "false">
<!ELEMENT test ((skip)?, (classifiers)?, (match)*, (prepare)?, ((sql|call|methodinvoker|dynamicsql|sub), result)?)>
  <!ATTLIST test
    name CDATA #REQUIRED
    java-object-support (on|off) "off"
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    failure-message CDATA #IMPLIED
    assert CDATA #IMPLIED
    expected-duration-millis CDATA #IMPLIED
    percentage-tolerance CDATA #IMPLIED>

<!-- Describing the batchtest element -->
<!ELEMENT paramset (param)+>
  <!ATTLIST paramset
    id CDATA #REQUIRED>
<!ELEMENT batchcall (stmt, (paramset)+)>
  <!ATTLIST batchcall
    connection-id CDATA #IMPLIED>
<!ELEMENT batchsql ((stmt)+)>
  <!ATTLIST batchsql
    connection-id CDATA #IMPLIED>
<!ELEMENT batchresult (updatecount)*>
  <!ATTLIST batchresult
    expected-count CDATA #IMPLIED
    failed-at CDATA #IMPLIED>
<!ELEMENT batchtest ((skip)?, (classifiers)?, (batchcall|batchsql), batchresult)>
  <!ATTLIST batchtest
    java-object-support (on|off) "off"
    failure-message CDATA #IMPLIED
    assert CDATA #IMPLIED
    name CDATA #REQUIRED>

<!-- Defining the diff element -->
<!ELEMENT diff ((skip)?, (classifiers)?, (match)*, (prepare)?, (sql|call), (sql|call))>
  <!ATTLIST diff
    name CDATA #REQUIRED
    java-object-support (on|off) "off"
    failure-message CDATA #IMPLIED
    assert CDATA #IMPLIED 
    multi-threaded (true|false) "false">

<!-- Defining the echo element -->
<!ELEMENT echo ((skip)?, (classifiers)?)>
  <!ATTLIST echo
    name CDATA #REQUIRED
    text CDATA #REQUIRED
    value CDATA #IMPLIED>

<!-- Defining the func element -->
<!ELEMENT func ((skip)?, (classifiers)?)>
  <!ATTLIST func
    name CDATA #REQUIRED
    lookup CDATA #REQUIRED
    connection-id CDATA #IMPLIED
    param0 CDATA #IMPLIED
    param1 CDATA #IMPLIED
    param2 CDATA #IMPLIED
    param3 CDATA #IMPLIED
    param4 CDATA #IMPLIED
    param5 CDATA #IMPLIED
    param6 CDATA #IMPLIED
    param7 CDATA #IMPLIED
    param8 CDATA #IMPLIED
    param9 CDATA #IMPLIED>

<!-- Describing the teardown element -->
<!ELEMENT teardown (((sql)*,(foreach)*)|(include)*)>

<!-- Describing the sqlunit element -->
<!ELEMENT sqlunit 
    ((connection)+, (setup)*, (test|batchtest|diff|echo|func)+, (teardown)*)>
  <!ATTLIST sqlunit
      name CDATA #IMPLIED>

=== scotas/ols/db/testSimilarity.xml
<?xml version="1.0"?>
<!DOCTYPE sqlunit SYSTEM "file:bin/sqlunit.dtd">
<sqlunit>
  <connection extern="db/sqlunit.properties" />
  
  <setup>
      <include file="db/schemaSimilarity.sql" />
  </setup>

<test name="Test Similarity" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select /*+ DOMAIN_INDEX_SORT */ lscore(1) f1,f2 from t1 where lcontains(f2, 'cefa cefa*',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias</col>
    </row>
    <row id="2">
      <col id="1" name="F1" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia</col>
    </row>
    <row id="3">
      <col id="1" name="F1" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia em salva</col>
    </row>
    <row id="4">
      <col id="1" name="F1" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias de tensão</col>
    </row>
    <row id="5">
      <col id="1" name="F1" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias / enxaquecas</col>
    </row>
    <row id="6">
      <col id="1" name="F1" type="NUMERIC">0.5</col>
      <col id="2" name="F2" type="VARCHAR">Intoxicação por antibióticos do grupo das cefalosporinas</col>
    </row>
  </resultset>
</result>
</test>

<test name="Test Similarity reverse order" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1) f1,f2 from t1 where lcontains(f2, 'cefa*',1) > 0 order by lscore(1) asc</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="NUMERIC">0.5</col>
      <col id="2" name="F2" type="VARCHAR">Intoxicação por antibióticos do grupo das cefalosporinas</col>
    </row>
    <row id="2">
      <col id="1" name="F1" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia em salva</col>
    </row>
    <row id="3">
      <col id="1" name="F1" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias / enxaquecas</col>
    </row>
    <row id="4">
      <col id="1" name="F1" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias de tensão</col>
    </row>
    <row id="5">
      <col id="1" name="F1" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias</col>
    </row>
    <row id="6">
      <col id="1" name="F1" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia</col>
    </row>
  </resultset>
</result>
</test>

<test name="Test Similarity no rows" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select /*+ DOMAIN_INDEX_SORT */ lscore(1) f1,f2 from t1 where lcontains(f2, 'cefa',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="Test Similarity changed SimilarityMethod" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 parameters('LogLevel:ALL;SimilarityMethod:org.apache.lucene.search.DefaultSimilarity')</stmt></sql>
  </prepare>
<sql>
  <stmt>select /*+ DOMAIN_INDEX_SORT */ lscore(1) f1,f2 from t1 where lcontains(f2, 'cefa cefa*',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="NUMERIC">0.4185726642608642578125</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia</col>
    </row>
    <row id="2">
      <col id="1" name="F1" type="NUMERIC">0.3058202266693115234375</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias</col>
    </row>
    <row id="3">
      <col id="1" name="F1" type="NUMERIC">0.303734958171844482421875</col>
      <col id="2" name="F2" type="VARCHAR">Intoxicação por antibióticos do grupo das cefalosporinas</col>
    </row>
    <row id="4">
      <col id="1" name="F1" type="NUMERIC">0.2616079151630401611328125</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia em salva</col>
    </row>
    <row id="5">
      <col id="1" name="F1" type="NUMERIC">0.1911376416683197021484375</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias de tensão</col>
    </row>
    <row id="6">
      <col id="1" name="F1" type="NUMERIC">0.1911376416683197021484375</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias / enxaquecas</col>
    </row>
  </resultset>
</result>
</test>

<test name="Test Similarity changed SimilarityMethod, reverse order" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1) f1,f2 from t1 where lcontains(f2, 'cefa*',1) > 0 order by lscore(1) asc</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="NUMERIC">0.456641495227813720703125</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias de tensão</col>
    </row>
    <row id="2">
      <col id="1" name="F1" type="NUMERIC">0.456641495227813720703125</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias / enxaquecas</col>
    </row>
    <row id="3">
      <col id="1" name="F1" type="NUMERIC">0.624999940395355224609375</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia em salva</col>
    </row>
    <row id="4">
      <col id="1" name="F1" type="NUMERIC">0.725644648075103759765625</col>
      <col id="2" name="F2" type="VARCHAR">Intoxicação por antibióticos do grupo das cefalosporinas</col>
    </row>
    <row id="5">
      <col id="1" name="F1" type="NUMERIC">0.730626404285430908203125</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleias</col>
    </row>
    <row id="6">
      <col id="1" name="F1" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">Cefaleia</col>
    </row>
  </resultset>
</result>
</test>

<test name="Test Similarity changed SimilarityMethod , no rows" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select /*+ DOMAIN_INDEX_SORT */ lscore(1) f1,f2 from t1 where lcontains(f2, 'cefa',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

  <teardown>
    <sql>
      <stmt>drop table t1</stmt>
    </sql>
  </teardown>
</sqlunit>

=== scotas/ols/db/testXMLType.xml
<?xml version="1.0"?>
<!DOCTYPE sqlunit SYSTEM "file:bin/sqlunit.dtd">
<sqlunit>
  <connection extern="db/sqlunit.properties" />
  
  <setup>
      <include file="db/schemaXMLType.sql" />
  </setup>

<test name="Index not populated yet" failure-message="Error with empty Simple SELECT">
<sql>
  <stmt>select sscore(1) sc, extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="Alter index rebuild" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 rebuild parameters('NormalizeScore:true;SyncMode:Deferred;LogLevel:ALL')</stmt></sql>
    <!-- wait auto commit 5 sec -->
    <sql><stmt>{call DBMS_LOCK.SLEEP(5)}</stmt></sql>
  </prepare>
<sql>
  <stmt>select sscore(1) sc ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
    </row>
  </resultset>
</result>
</test>

<test name="No rows example" failure-message="Error with empty Simple SELECT">
<sql>
  <stmt>select sscore(1) sc ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:aaa',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="Test alter index no rebuild" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 parameters('LogLevel:WARNING')</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('6', XMLType('&lt;emp id="6"&gt;&lt;name&gt;cheuk&lt;/name&gt;&lt;/emp&gt;'))</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('7', XMLType('&lt;emp id="7"&gt;&lt;name&gt;chau&lt;/name&gt;&lt;/emp&gt;'))</stmt></sql>
    <sql><stmt>UPDATE t1 SET f2 = XMLType('&lt;emp id="3"&gt;&lt;name&gt;Nipun&lt;/name&gt;&lt;/emp&gt;') WHERE f1 = '3'</stmt></sql>
    <sql><stmt>COMMIT</stmt></sql>
    <!-- wait auto commit 5 sec -->
    <sql><stmt>{call DBMS_LOCK.SLEEP(5)}</stmt></sql>
  </prepare>
<sql>
  <stmt>select sscore(1) sc ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:Nipun',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="One row example, after background process commit changes" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select sscore(1) sc ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:Nipun',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="disable AutoTuneMemory:false" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 parameters('~LogLevel:WARNING')</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('10', XMLType('&lt;emp id="10"&gt;&lt;name&gt;ravi marcelo&lt;/name&gt;&lt;/emp&gt;'))</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('16', XMLType('&lt;emp id="16"&gt;&lt;name&gt;marcelo&lt;/name&gt;&lt;/emp&gt;'))</stmt></sql>
    <sql><stmt>COMMIT</stmt></sql>
  </prepare>
  <call>
    <stmt>{call SolrDomainIndex.sync('IT1')}</stmt>
  </call>
  <result/>
</test>

<test name="Two row example" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select sscore(1) sc ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
    </row>
    <row id="2">
      <col id="1" name="SC" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

<test name="One row example, f1 condition" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select f1 ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:ravi AND f1_ti:10',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="VARCHAR">10</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

<test name="Count hits" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select SolrDomainIndex.countHits('IT1','name_tg:ravi') cnt from dual</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="CNT" type="NUMERIC">2</col>
    </row>
  </resultset>
</result>
</test>

<test name="Two row example, sort by id" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select /*+ DOMAIN_INDEX_SORT */ -1 sc ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:ravi','id_s desc',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">-1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
    </row>
    <row id="2">
      <col id="1" name="SC" type="NUMERIC">-1</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

<test name="One row example, filtering deleted rows" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>DELETE FROM t1 WHERE f1 = '1'</stmt></sql>
  </prepare>
<sql>
  <stmt>select sscore(1) sc ,extractValue(f2,'/emp/name/text()') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

  <teardown>
    <sql>
      <stmt>drop table t1</stmt>
    </sql>
  </teardown>
</sqlunit>
