=== scotas/ols/bin/sqlunit.dtd
<!--
  $Id: sqlunit.dtd,v 1.1 2010/09/06 18:31:53 mochoa Exp $
  $Source: /cvsroot/dbprism/odi/bin/sqlunit.dtd,v $
  This is the DTD for creating SQLUnit test cases in XML
-->

<!-- Describing common elements -->
<!ELEMENT skip (#PCDATA)>
  <!ATTLIST skip
    value (true|false) "false">
<!ELEMENT severity (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT classifiers ((severity)?, (category)?)>
<!ELEMENT stmt (#PCDATA)>
<!ELEMENT param (#PCDATA)>
  <!ATTLIST param
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    type CDATA #REQUIRED
    scale CDATA #IMPLIED
    typename CDATA #IMPLIED
    is-null (true|false) "false"
    inout (in|out|inout) "in">
<!ELEMENT sql (stmt, (param)*)>
  <!ATTLIST sql
    id CDATA #IMPLIED
    connection-id CDATA #IMPLIED>
<!ELEMENT call (stmt, (param)*)>
  <!ATTLIST call
    id CDATA #IMPLIED
    connection-id CDATA #IMPLIED>
<!ELEMENT arg EMPTY>
  <!ATTLIST arg
    name CDATA #REQUIRED
    value CDATA #IMPLIED
    type CDATA #IMPLIED>
<!ELEMENT typedef EMPTY>
  <!ATTLIST typedef
    typename CDATA #REQUIRED
    classname CDATA #REQUIRED>
<!ELEMENT constructorArgs (arg)*>
<!ELEMENT methodArgs (arg)*>
<!ELEMENT methodinvoker ((constructorArgs)*,(methodArgs)*)>
  <!ATTLIST methodinvoker
    static (true|false) "false"
    class CDATA #REQUIRED
    method CDATA #REQUIRED>
<!ELEMENT dynamicsql ((constructorArgs)*,(methodArgs)*)>
  <!ATTLIST dynamicsql
    static (true|false) "false"
    class CDATA #REQUIRED
    method CDATA #REQUIRED>
<!ELEMENT include EMPTY>
  <!ATTLIST include
    file CDATA #REQUIRED
    connection-id CDATA #IMPLIED>
<!ELEMENT set (((sql|call),result)?|(constructorArgs*,methodArgs*)?)>
  <!ATTLIST set
    name CDATA #REQUIRED
    value CDATA #IMPLIED
    static (true|false) "false"
    class CDATA #IMPLIED
    method CDATA #IMPLIED>

<!-- Describing the match element used for fuzzy matching -->
<!ELEMENT match (arg)*>
  <!ATTLIST match
    resultset-id CDATA #IMPLIED
    row-id CDATA #IMPLIED
    col-id CDATA #IMPLIED
    matcher CDATA #REQUIRED>

<!-- Describing a failure as a result of processing an SQL statement -->
<!ELEMENT code (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT exception ((code)?, (message)?)>

<!-- Describing the connection element -->
<!ELEMENT driver (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT jarfile-url (#PCDATA)>
<!ELEMENT datasource (#PCDATA)>
<!ELEMENT jndi (arg)*>
<!ELEMENT typemap (typedef)*>
<!ELEMENT connection (((driver,url,user,password,(jarfile-url)?)|(datasource,jndi))?)>
  <!ATTLIST connection 
    connection-id CDATA #IMPLIED
    extern CDATA #IMPLIED
    server-name CDATA #IMPLIED
    transaction-support (on|off|implicit) "on"
    reconnect-on-failure (on|off) "off">

<!-- Describing the foreach element -->
<!ELEMENT foreach (sql)*>
  <!ATTLIST foreach
    param CDATA #REQUIRED
    values CDATA #IMPLIED
    start CDATA #IMPLIED
    stop CDATA #IMPLIED
    step CDATA #IMPLIED
    count CDATA #IMPLIED>

<!-- Defining the funcdef element -->
<!ELEMENT funcdef EMPTY>
  <!ATTLIST funcdef
    name CDATA #REQUIRED
    query CDATA #REQUIRED
    description CDATA #IMPLIED>

<!-- Defining the subdef element -->
<!ELEMENT subdef ((param)*)>
  <!ATTLIST subdef
    name CDATA #REQUIRED
    query CDATA #REQUIRED
    description CDATA #IMPLIED
    type (sql|call) "sql">

<!-- Describing the setup element -->
<!ELEMENT setup ((set)*, (funcdef)*, (subdef)*, (((sql)*,(foreach)*)|(include)*))>

<!-- Defining the subparam element -->
<!ELEMENT subparam EMPTY>
  <!ATTLIST subparam
    name CDATA #REQUIRED
    value CDATA #REQUIRED>

<!-- Defining the sub element -->
<!ELEMENT sub ((subparam)*)>
  <!ATTLIST sub
    lookup CDATA #REQUIRED
    connection-id CDATA #IMPLIED>

<!-- Describing the prepare element -->
<!ELEMENT prepare ((set)*,(sql)*,(foreach)*)>

<!-- Describing the test element -->
<!ELEMENT updatecount (#PCDATA)>
<!ELEMENT col (#PCDATA)>
  <!ATTLIST col
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    type CDATA #REQUIRED>
<!ELEMENT row ((col)+)>
  <!ATTLIST row
    id CDATA #REQUIRED
    partial (true|false) "false">
<!ELEMENT resultset ((row)*)>
  <!ATTLIST resultset
    id CDATA #REQUIRED
    partial (true|false) "false"
    rowcount CDATA #IMPLIED
    order-by CDATA #IMPLIED>
<!ELEMENT field (#PCDATA|struct)*>
  <!ATTLIST field
    name CDATA #REQUIRED>
<!ELEMENT struct (field)*>
<!ELEMENT outparam (#PCDATA|resultset|struct)*>
  <!ATTLIST outparam
    id CDATA #REQUIRED
    name CDATA #IMPLIED
    type CDATA #REQUIRED>
<!ELEMENT result ((((outparam)*, (updatecount)?, (resultset)*)+|((outparam)*, exception))?)>
  <!ATTLIST result
    id CDATA #IMPLIED
    echo (true|false) "false">
<!ELEMENT test ((skip)?, (classifiers)?, (match)*, (prepare)?, ((sql|call|methodinvoker|dynamicsql|sub), result)?)>
  <!ATTLIST test
    name CDATA #REQUIRED
    java-object-support (on|off) "off"
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    failure-message CDATA #IMPLIED
    assert CDATA #IMPLIED
    expected-duration-millis CDATA #IMPLIED
    percentage-tolerance CDATA #IMPLIED>

<!-- Describing the batchtest element -->
<!ELEMENT paramset (param)+>
  <!ATTLIST paramset
    id CDATA #REQUIRED>
<!ELEMENT batchcall (stmt, (paramset)+)>
  <!ATTLIST batchcall
    connection-id CDATA #IMPLIED>
<!ELEMENT batchsql ((stmt)+)>
  <!ATTLIST batchsql
    connection-id CDATA #IMPLIED>
<!ELEMENT batchresult (updatecount)*>
  <!ATTLIST batchresult
    expected-count CDATA #IMPLIED
    failed-at CDATA #IMPLIED>
<!ELEMENT batchtest ((skip)?, (classifiers)?, (batchcall|batchsql), batchresult)>
  <!ATTLIST batchtest
    java-object-support (on|off) "off"
    failure-message CDATA #IMPLIED
    assert CDATA #IMPLIED
    name CDATA #REQUIRED>

<!-- Defining the diff element -->
<!ELEMENT diff ((skip)?, (classifiers)?, (match)*, (prepare)?, (sql|call), (sql|call))>
  <!ATTLIST diff
    name CDATA #REQUIRED
    java-object-support (on|off) "off"
    failure-message CDATA #IMPLIED
    assert CDATA #IMPLIED 
    multi-threaded (true|false) "false">

<!-- Defining the echo element -->
<!ELEMENT echo ((skip)?, (classifiers)?)>
  <!ATTLIST echo
    name CDATA #REQUIRED
    text CDATA #REQUIRED
    value CDATA #IMPLIED>

<!-- Defining the func element -->
<!ELEMENT func ((skip)?, (classifiers)?)>
  <!ATTLIST func
    name CDATA #REQUIRED
    lookup CDATA #REQUIRED
    connection-id CDATA #IMPLIED
    param0 CDATA #IMPLIED
    param1 CDATA #IMPLIED
    param2 CDATA #IMPLIED
    param3 CDATA #IMPLIED
    param4 CDATA #IMPLIED
    param5 CDATA #IMPLIED
    param6 CDATA #IMPLIED
    param7 CDATA #IMPLIED
    param8 CDATA #IMPLIED
    param9 CDATA #IMPLIED>

<!-- Describing the teardown element -->
<!ELEMENT teardown (((sql)*,(foreach)*)|(include)*)>

<!-- Describing the sqlunit element -->
<!ELEMENT sqlunit 
    ((connection)+, (setup)*, (test|batchtest|diff|echo|func)+, (teardown)*)>
  <!ATTLIST sqlunit
      name CDATA #IMPLIED>

=== scotas/ols/db/testSourceSmall.xml
<?xml version="1.0"?>
<!DOCTYPE sqlunit SYSTEM "file:bin/sqlunit.dtd">
<sqlunit>
  <connection extern="db/sqlunit.properties" />

  <setup>
      <include file="db/schemaSourceSmall.sql" />
  </setup>
  <test name="Optimize index">
     <call>
        <stmt>{call LuceneDomainIndex.optimize(?)}</stmt>
        <param id="1" type="VARCHAR">SOURCE_SMALL_LIDX</param>
      </call>
      <result/>
  </test>
  <test name="Count for type">
    <call>
      <stmt>{call
declare 
   cn NUMBER;
begin
   select count(*) into cn from test_source_small where lcontains(text,?)>0;
   if cn &lt; 60 then
     raise_application_error(-20101, 'Expected less than 60 rows, but found: ' || cn);
   end if;
end
}</stmt>
      <param id="1" type="VARCHAR" inout="in">type</param>
    </call>
    <result/>
  </test>

  <test name="Test pagination and lscore">
    <call>
      <stmt>{call 
declare 
  cn NUMBER := 0;
  lsc NUMBER;
  ltxt VARCHAR2(4000);
begin
  for c in (select /*+ DOMAIN_INDEX_SORT */ lscore(1) sc, text txt 
              from test_source_small where lcontains(text,'rownum:[1 TO 5] AND type',1)>0 order by lscore(1) desc) loop
    cn := cn + 1;
    lsc := c.sc;
    ltxt := c.txt;
  end loop;
  if cn &lt;> 5 then
     raise_application_error(-20101, 'Expected five rows, but found cn: ' || cn );
  end if;
  if round(lsc,4) &lt;> round(0.799999952,4) then
     raise_application_error(-20101, 'Expected last score around 0.8, but found lsc: ' || lsc);
  end if;
end
}</stmt>
    </call>
    <result/>
  </test>

  <test name="Count for varchar2">
    <call>
      <stmt>{call 
declare 
   cn NUMBER;
begin
   select count(*) into cn from test_source_small where lcontains(text,?)>0;
   dbms_output.put('Test ');
   if cn &lt; 230 then
     raise_application_error(-20101, 'Expected less thant 230, but found: ' || cn);
   end if;
end
}</stmt>
      <param id="1" type="VARCHAR" inout="in">varchar2</param>
    </call>
    <result/>
  </test>

  <test name="Count for number">
    <call>
      <stmt>{call 
declare 
   cn NUMBER;
begin
   select count(*) into cn from test_source_small where lcontains(text,?)>0;
   if cn &lt; 150 then
     raise_application_error(-20101, 'Expected less thant 150, but found: ' || cn);
   end if;
end
}</stmt>
      <param id="1" type="VARCHAR" inout="in">number</param>
    </call>
    <result/>
  </test>

  <teardown>
    <sql>
      <stmt>drop table test_source_small</stmt>
    </sql>
  </teardown>
</sqlunit>

=== scotas/ols/db/testIOT.xml
<?xml version="1.0"?>
<!DOCTYPE sqlunit SYSTEM "file:bin/sqlunit.dtd">
<sqlunit>
  <connection extern="db/sqlunit.properties" />
  
  <setup>
      <include file="db/schemaIOT.sql" />
  </setup>

<test name="One row example, padding" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 rebuild parameters('PerFieldAnalyzer:F1(org.apache.lucene.analysis.core.KeywordAnalyzer),id(org.apache.lucene.analysis.core.KeywordAnalyzer)')</stmt></sql>
  </prepare>
<sql>
  <stmt>select * from T1 where LCONTAINS(F2, 'ravi') > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
      <col id="3" name="F3" type="NUMERIC">3.46</col>
    </row>
  </resultset>
</result>
</test>

<test name="No rows example" failure-message="Error with empty Simple SELECT">
<sql>
  <stmt>select * from t1 where lcontains(f2, 'aaa') > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="Analyzer:org.apache.lucene.analysis.en.EnglishAnalyzer" failure-message="Error during sync">
  <prepare>
    <sql><stmt>alter index it1 parameters('Analyzer:org.apache.lucene.analysis.en.EnglishAnalyzer;AutoTuneMemory:false')</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES (6, 'he abhorred accents', 20.12)</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES (7, 'does', 25.98)</stmt></sql>
    <sql><stmt>UPDATE t1 SET f2 = 'Nipun' WHERE f1 = 3</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES (16, 'ravi marcelo', 30.01)</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES (17, 'marcelo', 30.99)</stmt></sql>
    <sql><stmt>commit</stmt></sql>
  </prepare>
  <call>
    <stmt>{call LuceneDomainIndex.sync('IT1')}</stmt>
  </call>
  <result/>
</test>

<test name="Optimize" failure-message="Error during optimize">
  <call>
    <stmt>{call LuceneDomainIndex.optimize('IT1')}</stmt>
  </call>
  <result/>
</test>

<test name="One row example, after optimize" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1) sc,f2 from t1 where lcontains(f2, 'ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
    </row>
    <row id="2">
      <col id="1" name="SC" type="NUMERIC">0.625000059604644775390625</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

<test name="One row example, after optimize" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1) sc,f2 from t1 where lcontains(f2, 'Nipun',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">Nipun</col>
    </row>
  </resultset>
</result>
</test>

<test name="lcontains outside where" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lcontains(f2,'ravi') sc from t1</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
    </row>
    <row id="2">
      <col id="1" name="SC" type="NUMERIC">0</col>
    </row>
    <row id="3">
      <col id="1" name="SC" type="NUMERIC">0</col>
    </row>
    <row id="4">
      <col id="1" name="SC" type="NUMERIC">0</col>
    </row>
    <row id="5">
      <col id="1" name="SC" type="NUMERIC">1</col>
    </row>
    <row id="6">
      <col id="1" name="SC" type="NUMERIC">0</col>
    </row>
  </resultset>
</result>
</test>

<test name="Multiple row example, range query" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select f1,f3 from t1 where lcontains(f2,'F3:[0 TO 30]',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="NUMERIC">1</col>
      <col id="2" name="F3" type="NUMERIC">3.46</col>
    </row>
    <row id="2">
      <col id="1" name="F1" type="NUMERIC">3</col>
      <col id="2" name="F3" type="NUMERIC">15.87</col>
    </row>
    <row id="3">
      <col id="1" name="F1" type="NUMERIC">6</col>
      <col id="2" name="F3" type="NUMERIC">20.12</col>
    </row>
    <row id="4">
      <col id="1" name="F1" type="NUMERIC">7</col>
      <col id="2" name="F3" type="NUMERIC">25.98</col>
    </row>
  </resultset>
</result>
</test>

<test name="Test delete" failure-message="Error with Simple DELETE">
<sql>
  <stmt>DELETE FROM t1 WHERE f2 = 'ravi'</stmt>
</sql>
<result>
  <updatecount>1</updatecount>
</result>
</test>

<test name="Filtering deleted rows, score not adjusted yet" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1) sc,f2 from t1 where lcontains(f2, 'ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">0.625000059604644775390625</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

<test name="Test stemmer" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1) sc,f2 from t1 where lcontains(f2, 'accents',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">he abhorred accents</col>
    </row>
  </resultset>
</result>
</test>

  <teardown>
    <sql>
      <stmt>drop table t1</stmt>
    </sql>
  </teardown>
</sqlunit>

=== scotas/ols/db/testJSon.xml
<?xml version="1.0"?>
<!DOCTYPE sqlunit SYSTEM "file:bin/sqlunit.dtd">
<sqlunit>
  <connection extern="db/sqlunit.properties" />
  
  <setup>
      <include file="db/schemaXMLType.sql" />
  </setup>

<test name="Index not populated yet" failure-message="Error with empty Simple SELECT">
<sql>
  <stmt>select sscore(1) sc, JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="Alter index rebuild" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 rebuild parameters('NormalizeScore:true;SyncMode:Deferred;LogLevel:ALL')</stmt></sql>
    <!-- wait auto commit 5 sec -->
    <sql><stmt>{call DBMS_LOCK.SLEEP(5)}</stmt></sql>
  </prepare>
<sql>
  <stmt>select sscore(1) sc, JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
    </row>
  </resultset>
</result>
</test>

<test name="No rows example" failure-message="Error with empty Simple SELECT">
<sql>
  <stmt>select sscore(1) sc, JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:aaa',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="Test alter index no rebuild" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 parameters('LogLevel:WARNING')</stmt></sql>
    <sql><stmt>insert into t1 values ('6', '{"id":6,"name":"cheuk"}')</stmt></sql>
    <sql><stmt>insert into t1 values ('7', '{"id":7,"name":"chau"}')</stmt></sql>
    <sql><stmt>update t1 set f2 = '{"id":3,"name":"Nipun"}' where f1 = '3'</stmt></sql>
    <sql><stmt>commit</stmt></sql>
    <!-- wait auto commit 5 sec -->
    <sql><stmt>{call DBMS_LOCK.SLEEP(5)}</stmt></sql>
  </prepare>
<sql>
  <stmt>select sscore(1) sc, JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:Nipun',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="One row example, after background process commit changes" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select sscore(1) sc, JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:Nipun',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="disable AutoTuneMemory:false" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>alter index it1 parameters('~LogLevel:WARNING')</stmt></sql>
    <sql><stmt>insert into t1 values ('10', '{"id":10,"name":"ravi marcelo"}')</stmt></sql>
    <sql><stmt>insert into t1 values ('16', '{"id":16,"name":"marcelo"}')</stmt></sql>
    <sql><stmt>commit</stmt></sql>
  </prepare>
  <call>
    <stmt>{call SolrDomainIndex.sync('IT1')}</stmt>
  </call>
  <result/>
</test>

<test name="Two row example" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select sscore(1) sc, JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
    </row>
    <row id="2">
      <col id="1" name="SC" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

<test name="One row example, f1 condition" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select f1, JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:ravi AND f1_ti:10',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="F1" type="VARCHAR">10</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

<test name="Count hits" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select SolrDomainIndex.countHits('IT1','name_tg:ravi') cnt from dual</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="CNT" type="NUMERIC">2</col>
    </row>
  </resultset>
</result>
</test>

<test name="Two row example, sort by id" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select /*+ DOMAIN_INDEX_SORT */ -1 sc ,JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:ravi','id_s desc',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">-1</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
    <row id="2">
      <col id="1" name="SC" type="NUMERIC">-1</col>
      <col id="2" name="F2" type="VARCHAR">ravi</col>
    </row>
  </resultset>
</result>
</test>

<test name="One row example, filtering deleted rows" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>DELETE FROM t1 WHERE f1 = '1'</stmt></sql>
  </prepare>
<sql>
  <stmt>select sscore(1) sc ,JSON_VALUE(f2,'$.name') f2 from t1 where scontains(f2, 'name_tg:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="SC" type="NUMERIC">0.625</col>
      <col id="2" name="F2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

  <teardown>
    <sql>
      <stmt>drop table t1</stmt>
    </sql>
  </teardown>
</sqlunit>

=== scotas/ols/db/testTermVector.xml
<?xml version="1.0"?>
<!DOCTYPE sqlunit SYSTEM "file:bin/sqlunit.dtd">
<sqlunit>
  <connection extern="db/sqlunit.properties" />
  
  <setup>
      <include file="db/schemaTermVector.sql" />
  </setup>

  <test name="select lscore(1) from t1 where lcontains(termvector,'two',1)>0" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1),termvector from t1 where lcontains(termvector,'two',1)>0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="c1" type="NUMERIC">0.411990344524383544921875</col>
      <col id="2" name="c2" type="VARCHAR">one two two three three three</col>
    </row>
    <row id="2">
      <col id="1" name="c1" type="NUMERIC">0.411990344524383544921875</col>
      <col id="2" name="c2" type="VARCHAR">one two two three three three</col>
    </row>
    <row id="3">
      <col id="1" name="c1" type="NUMERIC">0.411990344524383544921875</col>
      <col id="2" name="c2" type="VARCHAR">one two two three three three</col>
    </row>
    <row id="4">
      <col id="1" name="c1" type="NUMERIC">0.3433252871036529541015625</col>
      <col id="2" name="c2" type="VARCHAR">two two three three three four four four four</col>
    </row>
  </resultset>
</result>
</test>

  <!--test name="Test lfreqterms">
    <call>
      <stmt>{call 
declare 
  cn NUMBER := 0;
  lsc NUMBER;
  ltxt VARCHAR2(4000);
begin
  for c in (SELECT /*+ DOMAIN_INDEX_SORT */  termvector txt, lfreqterms(1) fqterms,lscore(1) sc 
              from t1 where lcontains(termvector,'two',1)>0) loop
    cn := cn + 1;
    lsc := c.sc;
    ltxt := c.txt;
  end loop;
  if cn &lt;> 4 OR round(lsc,4) &lt;> round(0.3433252871036529541015625,4) then
     raise_application_error(-20101, 'Expected four rows and found: ' || cn||' lsc= '||lsc);
  end if;
end
}</stmt>
    </call>
    <result/>
  </test-->

  <test name="Test deletion" failure-message="Error with Simple SELECT">
    <prepare>
      <sql><stmt>delete from t1 where rownum=1</stmt></sql>
    </prepare>
<sql>
  <stmt>select lscore(1),termvector from t1 where lcontains(termvector,'two',1)>0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="c1" type="NUMERIC">0.411990344524383544921875</col>
      <col id="2" name="c2" type="VARCHAR">one two two three three three</col>
    </row>
    <row id="2">
      <col id="1" name="c1" type="NUMERIC">0.411990344524383544921875</col>
      <col id="2" name="c2" type="VARCHAR">one two two three three three</col>
    </row>
    <row id="3">
      <col id="1" name="c1" type="NUMERIC">0.3433252871036529541015625</col>
      <col id="2" name="c2" type="VARCHAR">two two three three three four four four four</col>
    </row>
  </resultset>
</result>
</test>

  <teardown>
    <sql>
      <stmt>drop table t1</stmt>
    </sql>
  </teardown>
</sqlunit>

=== scotas/ols/db/testClob.xml
<?xml version="1.0"?>
<!DOCTYPE sqlunit SYSTEM "file:bin/sqlunit.dtd">
<sqlunit>
  <connection extern="db/sqlunit.properties" />
  
  <setup>
      <include file="db/schemaClob.sql" />
  </setup>

<test name="One row example" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lscore(1), to_char(f2) from t1 where lcontains(f3, 'f2:ravi',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="c1" type="NUMERIC">1</col>
      <col id="2" name="c2" type="VARCHAR">ravi</col>
    </row>
  </resultset>
</result>
</test>

<test name="No rows example" failure-message="Error with empty Simple SELECT">
<sql>
  <stmt>select lscore(1), to_char(f2) from t1 where lcontains(f3, 'f2:aaa',1) > 0</stmt>
</sql>
<result>
  <resultset id="1" rowcount="0"/>
</result>
</test>

<test name="Add/update new rows" failure-message="Error adding/updating new rows">
  <prepare>
    <sql><stmt>alter index it1 parameters('Analyzer:org.apache.lucene.analysis.core.StopAnalyzer;MaxBufferedDocs:500;AutoTuneMemory:false')</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('6', 'cheuk',101)</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('7', 'chau',102)</stmt></sql>
    <sql><stmt>UPDATE t1 SET f2 = 'Nipun', f3 = f3 WHERE f1 = '3'</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('16', 'ravi marcelo',101)</stmt></sql>
    <sql><stmt>INSERT INTO t1 VALUES ('17', 'marcelo',102)</stmt></sql>
  </prepare>
  <call>
    <stmt>{call LuceneDomainIndex.sync('IT1')}</stmt>
  </call>
  <result/>
</test>

<test name="multiple row select" failure-message="Error with Multiple rows SELECT">
<sql>
  <stmt>select /*+ DOMAIN_INDEX_SORT */ lscore(1), to_char(f2) from t1 where lcontains(f3, 'f2:ravi OR f5:data1',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="LSCORE(1)" type="NUMERIC">1</col>
      <col id="2" name="TO_CHAR(F2)" type="VARCHAR">ravi</col>
    </row>
    <row id="2">
      <col id="1" name="LSCORE(1)" type="NUMERIC">0.670330524444580078125</col>
      <col id="2" name="TO_CHAR(F2)" type="VARCHAR">ravi marcelo</col>
    </row>
    <row id="3">
      <col id="1" name="LSCORE(1)" type="NUMERIC">0.0604406781494617462158203125</col>
      <col id="2" name="TO_CHAR(F2)" type="VARCHAR">Nipun</col>
    </row>
    <row id="4">
      <col id="1" name="LSCORE(1)" type="NUMERIC">0.0604406781494617462158203125</col>
      <col id="2" name="TO_CHAR(F2)" type="VARCHAR">marcelo</col>
    </row>
    <row id="5">
      <col id="1" name="LSCORE(1)" type="NUMERIC">0.0604406781494617462158203125</col>
      <col id="2" name="TO_CHAR(F2)" type="VARCHAR">cheuk</col>
    </row>
    <row id="6">
      <col id="1" name="LSCORE(1)" type="NUMERIC">0.0604406781494617462158203125</col>
      <col id="2" name="TO_CHAR(F2)" type="VARCHAR">chau</col>
    </row>
  </resultset>
</result>
</test>

<test name="lcontains outside where" failure-message="Error with Simple SELECT">
<sql>
  <stmt>select lcontains(f3,'f2:ravi') sc from t1</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="c1" type="NUMERIC">1</col>
    </row>
    <row id="2">
      <col id="1" name="c1" type="NUMERIC">0</col>
    </row>
    <row id="3">
      <col id="1" name="c1" type="NUMERIC">1</col>
    </row>
    <row id="4">
      <col id="1" name="c1" type="NUMERIC">0</col>
    </row>
    <row id="5">
      <col id="1" name="c1" type="NUMERIC">0</col>
    </row>
    <row id="6">
      <col id="1" name="c1" type="NUMERIC">0</col>
    </row>
  </resultset>
</result>
</test>

<test name="select after deletions" failure-message="Error with Simple SELECT">
  <prepare>
    <sql><stmt>DELETE FROM t2 WHERE f4 = 102</stmt></sql>
  </prepare>
<sql>
  <stmt>select lscore(1), to_char(f2) from t1 where lcontains(f3, 'f2:marcelo',1) > 0</stmt>
</sql>
<result>
  <resultset id="1">
    <row id="1">
      <col id="1" name="c1" type="NUMERIC">1</col>
      <col id="2" name="c2" type="VARCHAR">ravi marcelo</col>
    </row>
  </resultset>
</result>
</test>

  <teardown>
    <sql>
      <stmt>drop table t1</stmt>
    </sql>
    <sql>
      <stmt>drop table t2</stmt>
    </sql>
  </teardown>
</sqlunit>
